"""Shared constants for the FAQ feature."""

DEFAULT_FAQ_SIMILARITY_THRESHOLD = 0.72
MIN_FAQ_SIMILARITY_THRESHOLD = 0.10
MAX_FAQ_SIMILARITY_THRESHOLD = 1.0

__all__ = [
    "DEFAULT_FAQ_SIMILARITY_THRESHOLD",
    "MIN_FAQ_SIMILARITY_THRESHOLD",
    "MAX_FAQ_SIMILARITY_THRESHOLD",
]
