from __future__ import annotations

import os

PREVIEW_MAX_DIMENSION = 112
TARGET_MAX_DIMENSION = 224
DEDUP_SIGNATURE_DIM = 16

FFMPEG_SCALE_EDGE = int(os.getenv("MODBOT_FFMPEG_MAX_EDGE", "1536"))
FRAME_MAX_INLINE_BYTES = int(os.getenv("MODBOT_FRAME_MAX_INLINE_BYTES", "7000000"))
FRAME_MIN_EDGE = int(os.getenv("MODBOT_FRAME_MIN_EDGE", "512"))
FFMPEG_TIMEOUT_SECONDS = float(os.getenv("MODBOT_FFMPEG_TIMEOUT", "45"))

SUPPRESS_OPENCV_STDERR = os.environ.get("MODBOT_SUPPRESS_OPENCV_STDERR", "1").lower()
SUPPRESS_OPENCV_STDERR = SUPPRESS_OPENCV_STDERR not in {"0", "false", "off"}
