from __future__ import annotations

import discord

from modules.config.premium_plans import PLAN_CORE

from .base import (
    NSFW_PFP_DEFAULT_CHOICES,
    NSFW_PFP_DEFAULT_MESSAGE,
    Setting,
)


def build_nsfw_settings() -> dict[str, Setting]:
    return {
        "nsfw-verbose": Setting(
            name="nsfw-verbose",
            description="Post a detailed scan report embed in the same channel as the scanned media.",
            setting_type=bool,
            default=False,
            choices=["true", "false"],
            description_key="modules.config.settings_schema.nsfw-verbose.description",
        ),
        "nsfw-channel": Setting(
            name="nsfw-channel",
            description="Channel where NSFW violations are logged with a preview of the media.",
            setting_type=discord.TextChannel,
            hidden=True,
            description_key="modules.config.settings_schema.nsfw-channel.description",
        ),
        "nsfw-channel-notify": Setting(
            name="nsfw-channel-notify",
            description="Send a notification embed to the channel when NSFW content is removed.",
            setting_type=bool,
            default=True,
            choices=["true", "false"],
            description_key="modules.config.settings_schema.nsfw-channel-notify.description",
        ),
        "nsfw-enabled": Setting(
            name="nsfw-enabled",
            description="Enable NSFW scanning for messages, reactions, and avatars (other toggles still apply).",
            setting_type=bool,
            default=True,
            choices=["true", "false"],
            description_key="modules.config.settings_schema.nsfw-enabled.description",
        ),
        "nsfw-text-enabled": Setting(
            name="nsfw-text-enabled",
            description="Enable NSFW scanning for message text content.",
            setting_type=bool,
            default=False,
            choices=["true", "false"],
            required_plans=PLAN_CORE,
        ),
        "nsfw-text-strikes-only": Setting(
            name="nsfw-text-strikes-only",
            description="Only run NSFW text detection for members with active strikes.",
            setting_type=bool,
            default=False,
            choices=["true", "false"],
            required_plans=PLAN_CORE,
        ),
        "nsfw-detection-action": Setting(
            name="nsfw-detection-action",
            description="Action to take when a user posts NSFW content.",
            setting_type=list[str],
            default=["delete", "strike"],
            hidden=True,
            choices=["strike", "kick", "ban", "timeout", "delete"],
            description_key="modules.config.settings_schema.nsfw-detection-action.description",
        ),
        "nsfw-text-action": Setting(
            name="nsfw-text-action",
            description="Action to take when NSFW content is detected in message text.",
            setting_type=list[str],
            default=["delete"],
            hidden=True,
            required_plans=PLAN_CORE,
            choices=["strike", "kick", "ban", "timeout", "delete"],
            description_key="modules.config.settings_schema.nsfw-text-action.description",
        ),
        "nsfw-text-excluded-channels": Setting(
            name="nsfw-text-excluded-channels",
            description="Channels where NSFW text scanning is disabled.",
            setting_type=list[discord.TextChannel],
            default=[],
            required_plans=PLAN_CORE,
            hidden=True,
            description_key="modules.config.settings_schema.nsfw-text-excluded-channels.description",
        ),
        "nsfw-detection-categories": Setting(
            name="nsfw-detection-categories",
            description="Categories considered NSFW for detection.",
            setting_type=list[str],
            default=[
                "violence_graphic",
                "sexual"
            ],
            required_plans=PLAN_CORE,
            hidden=True,
            description_key="modules.config.settings_schema.nsfw-detection-categories.description",
        ),
        "nsfw-text-categories": Setting(
            name="nsfw-text-categories",
            description="Categories considered NSFW for text detection.",
            setting_type=list[str],
            default=[
                "violence_graphic",
                "sexual",
            ],
            required_plans=PLAN_CORE,
            hidden=True,
            description_key="modules.config.settings_schema.nsfw-text-categories.description",
        ),
        "nsfw-high-accuracy": Setting(
            name="nsfw-high-accuracy",
            description="Enable high-accuracy NSFW scans for more reliable detection. Accelerated only.",
            setting_type=bool,
            default=False,
            required_plans=PLAN_CORE,
            choices=["true", "false"],
            description_key="modules.config.settings_schema.nsfw-high-accuracy.description",
        ),
        "threshold": Setting(
            name="threshold",
            description="Threshold for NSFW detection confidence. Lower values are more sensitive.",
            setting_type=float,
            default=0.70,
            hidden=True,
            description_key="modules.config.settings_schema.threshold.description",
        ),
        "nsfw-text-threshold": Setting(
            name="nsfw-text-threshold",
            description="Threshold for NSFW text detection confidence. Lower values are more sensitive.",
            setting_type=float,
            default=0.70,
            hidden=True,
            required_plans=PLAN_CORE,
            description_key="modules.config.settings_schema.nsfw-text-threshold.description",
        ),
        "check-pfp": Setting(
            name="check-pfp",
            description="Check the profile picture of the user for NSFW content.",
            setting_type=bool,
            default=False, # False by default to avoid unnecessary API calls
            choices=["true", "false"],
            required_plans=PLAN_CORE,
            description_key="modules.config.settings_schema.check-pfp.description",
        ),
        "nsfw-pfp-action": Setting(
            name="nsfw-pfp-action",
            description="Action to take when a user sets an NSFW profile picture.",
            setting_type=list[str],
            default=["kick"],
            choices=["strike", "strike:2d", "kick", "ban", "timeout:1d", "timeout:7d"],
            description_key="modules.config.settings_schema.nsfw-pfp-action.description",
        ),
        "nsfw-pfp-message": Setting(
            name="nsfw-pfp-message",
            description="The message to send when a player has had their profile picture flagged.",
            setting_type=str,
            default=NSFW_PFP_DEFAULT_MESSAGE,
            choices=list(NSFW_PFP_DEFAULT_CHOICES),
            required_plans=PLAN_CORE,
            description_key="modules.config.settings_schema.nsfw-pfp-message.description",
        ),
        "unmute-on-safe-pfp": Setting(
            name="unmute-on-safe-pfp",
            description="Remove timeout of a user once they have changed their profile picture to something appropriate.",
            setting_type=bool,
            default=False,
            choices=["true", "false"],
            required_plans=PLAN_CORE,
            description_key="modules.config.settings_schema.unmute-on-safe-pfp.description",
        ),
        "scan-age-restricted": Setting(
            name="scan-age-restricted",
            description="Scan age-restricted (NSFW) channels. When off, NSFW channels are skipped.",
            setting_type=bool,
            default=True,
            choices=["true", "false"],
            description_key="modules.config.settings_schema.scan-age-restricted.description",
        ),
        "check-tenor-gifs": Setting(
            name="check-tenor-gifs",
            description="Apply punishments when NSFW content is detected in Tenor GIFs.",
            setting_type=bool,
            default=False,
            choices=["true", "false"],
            description_key="modules.config.settings_schema.check-tenor-gifs.description",
        ),
    }
